[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd frontend && pnpm install"]

[phases.build]
cmds = ["cd frontend && pnpm run build"]

[start]
cmd = "npx serve frontend/dist -s -l tcp://0.0.0.0:${PORT:-3000}"